services:
  postgres:
    image: postgres:16-alpine
    container_name: tenpo-postgres
    environment:
      POSTGRES_DB: tenpo_db
      POSTGRES_USER: tenpo
      POSTGRES_PASSWORD: tenpo_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tenpo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tenpo -d tenpo_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: tenpo-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - tenpo-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  redisdata:

networks:
  tenpo-network:
    driver: bridge
