spring:
    config:
        activate:
            on-profile: docker_full
    docker:
        compose:
            enabled: true
            lifecycle-management: start-and-stop

audit:
    kafka:
        bootstrap-servers: kafka:29092
